import {
  DEFAULT_DOKUHA_STATE,
  DEFAULT_DOKUHA_SYSTEM_STATE,
  DOKUHA_ACCESSORIES,
  DOKUHA_ATTACHMENT_LEVEL_LABELS,
  DOKUHA_ATTACHMENT_THRESHOLDS,
  DOKUHA_DISORDER_LABELS,
  DOKUHA_DISORDERS,
  DOKUHA_DYNAMIC_EMOTION_LABELS,
  DOKUHA_DYNAMIC_EMOTIONS,
  DOKUHA_EVENT_PHASES,
  DOKUHA_EVENT_SUMMARY_LIMIT,
  DOKUHA_EVENT_TYPES,
  DOKUHA_FAMILIARITY_MAX,
  DOKUHA_FAMILIARITY_SCALE,
  DOKUHA_FAMILIARITY_TIER_LABELS,
  DOKUHA_FAMILIARITY_TIER_THRESHOLDS,
  DOKUHA_LONG_TERM_EMOTION_LABELS,
  DOKUHA_LONG_TERM_EMOTIONS,
  DOKUHA_MODE_LABELS,
  DOKUHA_MODES,
  DOKUHA_OUTFITS,
  DOKUHA_PHYSIOLOGY_MOOD_LINES,
  DOKUHA_PHYSIOLOGY_PHASE_LABELS,
  DOKUHA_PHYSIOLOGY_PHASES,
  DOKUHA_PMDD_CYCLE_RULE,
  DOKUHA_PMDD_JUDGMENTS,
  DOKUHA_RELATIONSHIP_STAGE_LABELS,
  DOKUHA_RELATIONSHIP_THRESHOLDS,
  DOKUHA_STANDING_MODES,
  calculatePMDDInterval,
  computePMDDCycleDay,
  deriveFamiliarityProfile,
  derivePhysiologyProfile,
  ensureMetadataHasPMDDAnchor,
  formatMetadataTimestamp,
  generatePMDDJudgment,
  normalizeAccessories,
  normalizeContextNotes,
  normalizeDisorderActive,
  normalizeDokuhaState,
  normalizeDokuhaSystemState,
  normalizeEventSummary,
  normalizeMetadata,
  sanitizeContextNote,
  timeObjectToDate,
  type DokuhaAccessory,
  type DokuhaAttachmentLevel,
  type DokuhaContextNotes,
  type DokuhaDisorder,
  type DokuhaDynamicEmotion,
  type DokuhaEventPhase,
  type DokuhaEventSummary,
  type DokuhaEventType,
  type DokuhaFamiliarityProfile,
  type DokuhaFamiliarityTier,
  type DokuhaLongTermEmotion,
  type DokuhaMetadata,
  type DokuhaMode,
  type DokuhaOutfit,
  type DokuhaPhysiologyPhase,
  type DokuhaPhysiologyProfile,
  type DokuhaRelationshipStage,
  type DokuhaStandingMode,
  type DokuhaState,
  type DokuhaSystemState,
  type DokuhaTimeObject
} from '../../dokuha/state';

export {
  DEFAULT_DOKUHA_STATE,
  DEFAULT_DOKUHA_SYSTEM_STATE,
  DOKUHA_ACCESSORIES,
  DOKUHA_ATTACHMENT_LEVEL_LABELS,
  DOKUHA_ATTACHMENT_THRESHOLDS,
  DOKUHA_DISORDER_LABELS,
  DOKUHA_DISORDERS,
  DOKUHA_DYNAMIC_EMOTION_LABELS,
  DOKUHA_DYNAMIC_EMOTIONS,
  DOKUHA_EVENT_PHASES,
  DOKUHA_EVENT_SUMMARY_LIMIT,
  DOKUHA_EVENT_TYPES,
  DOKUHA_FAMILIARITY_MAX,
  DOKUHA_FAMILIARITY_SCALE,
  DOKUHA_FAMILIARITY_TIER_LABELS,
  DOKUHA_FAMILIARITY_TIER_THRESHOLDS,
  DOKUHA_LONG_TERM_EMOTION_LABELS,
  DOKUHA_LONG_TERM_EMOTIONS,
  DOKUHA_MODE_LABELS,
  DOKUHA_MODES,
  DOKUHA_OUTFITS,
  DOKUHA_PHYSIOLOGY_MOOD_LINES,
  DOKUHA_PHYSIOLOGY_PHASE_LABELS,
  DOKUHA_PHYSIOLOGY_PHASES,
  DOKUHA_PMDD_CYCLE_RULE,
  DOKUHA_PMDD_JUDGMENTS,
  DOKUHA_RELATIONSHIP_STAGE_LABELS,
  DOKUHA_RELATIONSHIP_THRESHOLDS,
  DOKUHA_STANDING_MODES,
  calculatePMDDInterval,
  computePMDDCycleDay,
  deriveFamiliarityProfile,
  derivePhysiologyProfile,
  ensureMetadataHasPMDDAnchor,
  formatMetadataTimestamp,
  generatePMDDJudgment,
  normalizeAccessories,
  normalizeContextNotes,
  normalizeDisorderActive,
  normalizeDokuhaState,
  normalizeDokuhaSystemState,
  normalizeEventSummary,
  normalizeMetadata,
  sanitizeContextNote,
  timeObjectToDate,
  type DokuhaAccessory,
  type DokuhaAttachmentLevel,
  type DokuhaContextNotes,
  type DokuhaDisorder,
  type DokuhaDynamicEmotion,
  type DokuhaEventPhase,
  type DokuhaEventSummary,
  type DokuhaEventType,
  type DokuhaFamiliarityProfile,
  type DokuhaFamiliarityTier,
  type DokuhaLongTermEmotion,
  type DokuhaMetadata,
  type DokuhaMode,
  type DokuhaOutfit,
  type DokuhaPhysiologyPhase,
  type DokuhaPhysiologyProfile,
  type DokuhaRelationshipStage,
  type DokuhaStandingMode,
  type DokuhaState,
  type DokuhaSystemState,
  type DokuhaTimeObject
};

export const DOKUHA_STAT_KEY = 'stat_data';
export const DOKUHA_NAMESPACE = 'dokuha';

export const DOKUHA_ALLOWED_FIELD_PATHS = [
  '/dokuha/familiarity/points',
  '/dokuha/coreStates/mode',
  '/dokuha/coreStates/relationshipStage',
  '/dokuha/coreStates/attachmentLevel',
  '/dokuha/mentalStates/disorderActive',
  '/dokuha/mentalStates/longTermEmotion',
  '/dokuha/mentalStates/dynamicEmotion',
  '/dokuha/outfit',
  '/dokuha/accessories',
  '/dokuha/current_location',
  '/dokuha/current_event/type',
  '/dokuha/current_event/name',
  '/dokuha/current_event/phase',
  '/dokuha/current_event/start_time',
  '/dokuha/metadata/last_pmdd_time',
  '/dokuha/metadata/pmdd_cycle_anchor',
  '/dokuha/metadata/pmdd_followup_consumed',
  '/dokuha/context_notes/event_summaries',
  '/dokuha/context_notes/pending_event_summary',
  '/dokuha/context_notes/pending_new_event_hint'
] as const;

export const DOKUHA_SYSTEM_ALLOWED_FIELD_PATHS = [
  '/system',
  '/system/current_time',
  '/system/time_advance',
  '/system/time_set_to',
  '/system/event_start/name',
  '/system/event_start/type'
] as const;

export function cloneJson<T>(value: unknown, fallback: T): T {
  if (value === undefined || value === null) return fallback;
  try {
    return JSON.parse(JSON.stringify(value)) as T;
  } catch (_) {
    return fallback;
  }
}

export function makeDefaultDokuhaState(): DokuhaState {
  return cloneJson(DEFAULT_DOKUHA_STATE, DEFAULT_DOKUHA_STATE);
}

export function makeDefaultDokuhaSystemState(): DokuhaSystemState {
  return cloneJson(DEFAULT_DOKUHA_SYSTEM_STATE, DEFAULT_DOKUHA_SYSTEM_STATE);
}
