/**
   * Prewarms DOKUHA expression PNGs into the browser image cache.
   * Generated by scripts/build-dokuha-exp-regex.ts.
 */
(function () {
  'use strict';

  const CURRENT_ROOT = typeof window !== 'undefined' ? window : globalThis;
  const DEFAULT_APP_BASE_URL = 'https://hasheeper.github.io/project-dokuha';
  const ASSET_REFS = {"base":["nightwear","nude","streetwear_full","streetwear_inner","underwear"],"face":["face_blush","face_default","face_pale","face_shadow"],"eye":["eye_closed","eye_cry","eye_dizzy","eye_half_1","eye_half_2","eye_half_3","eye_half_4","eye_half_5","eye_jitome_1","eye_jitome_2","eye_line","eye_normal","eye_smile_1","eye_smile_2","eye_socket","eye_star","eye_wide_1","eye_wide_2","eye_xd"],"mouth":["mouth_awawa","mouth_blank_1","mouth_blank_2","mouth_down_1","mouth_down_2","mouth_drool","mouth_gritting_teeth","mouth_huh_1","mouth_huh_2","mouth_neutral","mouth_open","mouth_pout","mouth_smile","mouth_smirk","mouth_tongue"],"brow":["brow_down","brow_normal","brow_up"],"other":["ear_face_pale","eye_tears_1","eye_tears_2","eye_tears_3","eye_tears_4","face_pale_up","face_shadow_up","headphones","mask_down","mask_up","sweat"]};
  const CACHE_KEY = '__DOKUHA_EXP_IMAGE_CACHE__';

  function resolveBridgeHost() {
    try { if (CURRENT_ROOT.DOKUHA_ST_HOST) return CURRENT_ROOT.DOKUHA_ST_HOST; } catch (_) {}
    try { if (CURRENT_ROOT.DOKUHA_ST_HOST_ROOT?.DOKUHA_ST_HOST) return CURRENT_ROOT.DOKUHA_ST_HOST_ROOT.DOKUHA_ST_HOST; } catch (_) {}
    try { if (CURRENT_ROOT.parent?.DOKUHA_ST_HOST) return CURRENT_ROOT.parent.DOKUHA_ST_HOST; } catch (_) {}
    try { if (CURRENT_ROOT.top?.DOKUHA_ST_HOST) return CURRENT_ROOT.top.DOKUHA_ST_HOST; } catch (_) {}
    return {};
  }

  function readGlobalString(key) {
    const targets = [CURRENT_ROOT];
    try { targets.push(CURRENT_ROOT.parent); } catch (_) {}
    try { targets.push(CURRENT_ROOT.top); } catch (_) {}
    for (const target of targets) {
      try {
        if (typeof target?.[key] === 'string' && target[key].trim()) return target[key].trim();
      } catch (_) {}
    }
    return '';
  }

  function trimTrailingSlash(value) {
    return typeof value === 'string' ? value.trim().replace(/\/+$/, '') : '';
  }

  function resolveAssetBaseUrl() {
    const bridgeHost = resolveBridgeHost();
    const explicit = readGlobalString('DOKUHA_ASSET_BASE_URL');
    if (explicit) return trimTrailingSlash(explicit);
    if (typeof bridgeHost.assetBaseUrl === 'string' && bridgeHost.assetBaseUrl.trim()) {
      return trimTrailingSlash(bridgeHost.assetBaseUrl);
    }
    const appBase = trimTrailingSlash(
      readGlobalString('DOKUHA_APP_BASE_URL')
        || bridgeHost.appBaseUrl
        || DEFAULT_APP_BASE_URL
    );
    return appBase + '/dokuha-assets/standing';
  }

  function assetUrl(baseUrl, group, name) {
    const folders = {
      base: 'base',
      face: 'expression/face_fx',
      eye: 'expression/eyes',
      mouth: 'expression/mouth',
      brow: 'expression/brow',
      other: 'expression/other'
    };
    return baseUrl + '/' + folders[group] + '/' + encodeURIComponent(name) + '.png';
  }

  function getAllAssetUrls(baseUrl) {
    return [].concat(
      ASSET_REFS.base.map((name) => assetUrl(baseUrl, 'base', name)),
      ASSET_REFS.face.map((name) => assetUrl(baseUrl, 'face', name)),
      ASSET_REFS.mouth.map((name) => assetUrl(baseUrl, 'mouth', name)),
      ASSET_REFS.eye.map((name) => assetUrl(baseUrl, 'eye', name)),
      ASSET_REFS.brow.map((name) => assetUrl(baseUrl, 'brow', name)),
      ASSET_REFS.other.map((name) => assetUrl(baseUrl, 'other', name))
    );
  }

  function getCacheRoot() {
    const candidates = [CURRENT_ROOT];
    try { candidates.push(CURRENT_ROOT.parent); } catch (_) {}
    try { candidates.push(CURRENT_ROOT.top); } catch (_) {}
    for (const target of candidates) {
      try {
        if (target && target.Object) return target;
      } catch (_) {}
    }
    return CURRENT_ROOT;
  }

  function warmImageCache(urls) {
    const root = getCacheRoot();
    let cache;
    try {
      cache = root[CACHE_KEY] || (root[CACHE_KEY] = Object.create(null));
    } catch (_) {
      cache = CURRENT_ROOT[CACHE_KEY] || (CURRENT_ROOT[CACHE_KEY] = Object.create(null));
    }

    urls.forEach((url) => {
      if (!url || cache[url]) return;
      const image = new Image();
      cache[url] = { status: 'loading', image };
      image.decoding = 'async';
      try { image.fetchPriority = 'low'; } catch (_) {}
      image.onload = function () { cache[url].status = 'ready'; };
      image.onerror = function () { cache[url].status = 'error'; };
      image.src = url;
    });
  }

  function warmExpressionAssets() {
    const baseUrl = resolveAssetBaseUrl();
    const urls = getAllAssetUrls(baseUrl);
    warmImageCache(urls.slice(0, 8));
    setTimeout(() => warmImageCache(urls.slice(8)), 300);
    return { baseUrl, count: urls.length };
  }

  try {
    const runtime = CURRENT_ROOT.DOKUHAMainRuntime || {};
    runtime.warmExpressionAssets = warmExpressionAssets;
    CURRENT_ROOT.DOKUHAMainRuntime = runtime;
  } catch (_) {}

  const result = warmExpressionAssets();
  try {
    console.info('[DOKUHA Asset Cache] warming expression PNG cache:', result);
  } catch (_) {}
})();
